# Generated by Django 3.1.7 on 2021-03-27 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_auto_20210327_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchoffice',
            name='num_citas',
        ),
    ]
